name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v5
      - run: apt-get update
      - run: apt-get install cowsay
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt